services:
  webserver-1:
    image: docker.io/nginx:1-alpine
    hostname: webhost
    deploy:
      replicas: 3
    networks:
      web-net:

  webserver-2:
    image: docker.io/nginx:1-alpine
    # No hostname
    deploy:
      replicas: 3
    networks:
      web-net:

networks:
  web-net:
    attachable: true
