FROM python:alpine
WORKDIR /code
COPY requirements.txt requirements.txt
COPY api_and_gunicorn.py /code/api.py
RUN pip install -r requirements.txt --no-cache-dir

RUN apk add --no-cache binutils
RUN pip install --no-cache-dir pyinstaller
# implicit dependencies(hidden imports) need to be added
RUN pyinstaller api.py --hidden-import "gunicorn.glogging" --hidden-import "gunicorn.workers.sync"

CMD ./dist/api/api
