FROM python as builder
LABEL stage=builder
ENV BOOTLOADER_CC=musl-gcc
WORKDIR /code
COPY requirements.txt requirements.txt
COPY api_and_gunicorn.py /code/api.py
RUN pip install -r requirements.txt --no-cache-dir

RUN apt update && apt install -y patchelf
RUN pip install --no-cache-dir pyinstaller staticx
# implicit dependencies(hidden imports) need to be added
# collect-submodules just collects all subomdules of a package or module
RUN pyinstaller api.py --onefile --collect-submodules "falcon" \
                                  --hidden-import "gunicorn.glogging" \
                                  --hidden-import "gunicorn.workers.sync" \
                                  --hidden-import "uuid" \
                                  --hidden-import "cgi" \
                                  --hidden-import "xml.etree" \
                                  --hidden-import "xml.etree.ElementTree"

RUN staticx ./dist/api ./dist/static_binary_api
RUN mkdir tmp
#CMD ./dist/static_binary_api
#CMD ./dist/api

FROM scratch
COPY --from=builder /code/dist/static_binary_api /api
COPY --from=builder /code/tmp /tmp
CMD ["/api"]