FROM debian:13-slim

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update \
  && apt upgrade -y \
  && apt autoclean -y \
  && apt autoremove -y \
  && apt clean -y \
  && rm -rf /var/lib/apt/lists* /tmp/* /var/tmp/*
